import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const body=html.slice(html.indexOf('<body>'));
if(body.includes('data-page="datafetch"')||body.includes('<section id="datafetch"')) throw new Error('in-app acquisition UI still present');
if(body.includes('アナスロSafari起動')||body.includes('アナスロ取得実行')) throw new Error('Shortcut acquisition UI still present');
if(!body.includes('data-page="extimport"')||!body.includes('<section id="extimport"')) throw new Error('JSON import UI missing');
if(!body.includes('id="RELAY_CREATE"')||!body.includes('id="RELAY_RECEIVE"')) throw new Error('Launcher relay UI missing');
if(!html.includes('v4.5.3')) throw new Error('v4.5.3 display missing');
if(!html.includes('ジャグラー・ハナハナ設定判別')) throw new Error('combined title missing');
if(!body.includes('data-family="hanahana"')) throw new Error('family toggle missing');
if(!body.includes('data-page="jdata"')||!body.includes('<section id="jdata"')) throw new Error('Juggler data site UI missing');
const m=html.match(/<script>([\s\S]*?)<\/script>/i); if(!m) throw new Error('script missing');
let code=m[1];
const cut=code.indexOf('let didRestore=restoreSavedState();'); if(cut<0) throw new Error('init cut missing');
code=code.slice(0,cut)+`globalThis.__API={externalJudge,expectedSetting,normalizeExternalDay,normalizeExternalBulkImport,importRelayBulk,syncShopMasterFromExternalDays,storeDataShopNames,jdataMetrics,renderJugglerDataSite,_external(){return externalDays},_shops(){return shops},_set(x){if(x.shops)shops=x.shops;if(x.externalDays)externalDays=x.externalDays;}};\n})();`;
function fakeElement(){const base={value:'',checked:false,innerHTML:'',textContent:'',className:'',style:{},dataset:{},files:[],disabled:false,classList:{add(){},remove(){},toggle(){},contains(){return false}},appendChild(){},append(){},remove(){},click(){},focus(){},scrollIntoView(){},setAttribute(){},removeAttribute(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return fakeElement()},closest(){return fakeElement()}};return new Proxy(base,{get(t,p){if(p in t)return t[p];if(p==='length')return 0;return undefined},set(t,p,v){t[p]=v;return true}})}
const elems=new Map();
const document={getElementById(id){if(!elems.has(id))elems.set(id,fakeElement());return elems.get(id)},querySelectorAll(){return[]},querySelector(){return fakeElement()},createElement(){return fakeElement()},body:fakeElement(),addEventListener(){},removeEventListener(){}};
const storage=new Map();
const URLClass=URL; URLClass.createObjectURL=()=> 'blob:x'; URLClass.revokeObjectURL=()=>{};
const sandbox={console,document,window:null,location:{protocol:'https:',origin:'https://example.netlify.app',reload(){}},localStorage:{setItem(k,v){storage.set(k,String(v))},getItem(k){return storage.has(k)?storage.get(k):null},removeItem(k){storage.delete(k)}},indexedDB:undefined,confirm(){return true},alert(){},prompt(){return null},navigator:{},Blob:function(){},URL:URLClass,FileReader:function(){},setTimeout,clearTimeout,Date,Math,JSON,Map,Set,Promise,Number,String,Array,Object,Infinity,NaN,parseInt,isFinite,crypto:globalThis.crypto,fetch:async()=>{throw new Error('no net')},performance:globalThis.performance};
sandbox.window=sandbox;sandbox.window.addEventListener=()=>{};sandbox.window.removeEventListener=()=>{};
vm.createContext(sandbox); vm.runInContext(code,sandbox,{timeout:10000});
const a=sandbox.__API;
const j=a.externalJudge('im',8000,32,31,1500); if(Math.abs(j.q.reduce((x,y)=>x+y,0)-1)>1e-9)throw new Error('judge broken');
const raw={format:'juggler-external-import',version:5,source:'ana-slo',shop:'テスト店',date:'2026-08-23',sourceUrl:'https://ana-slo.com/x',machines:[{machine:'im',sourceMachineName:'ネオアイムジャグラーEX',tableNo:'1',games:8000,diff:1500,bb:32,rb:31}]};
const day=a.normalizeExternalDay(raw,{source:raw.source,shop:raw.shop});
if(day.machines.length!==1||day.machines[0].q.length!==6)throw new Error('JSON normalization/judge broken');
const bulk=await a.normalizeExternalBulkImport({format:'juggler-external-import-bulk',version:5,source:'ana-slo',shop:'テスト店',days:[{date:'2026-08-23',sourceUrl:'https://ana-slo.com/x',machines:raw.machines},{date:'2026-08-22',sourceUrl:'https://ana-slo.com/y',machines:raw.machines}]});
if(!bulk.bulk||bulk.days.length!==2||bulk.days.some(d=>d.machines[0].q.length!==6))throw new Error('bulk JSON import compatibility broken');
a._set({shops:[],externalDays:[day]});
if(a.syncShopMasterFromExternalDays({save:false})!==1)throw new Error('external shop master backfill broken');
if(!a.storeDataShopNames().includes('テスト店'))throw new Error('shared shop names missing JSON-imported shop');
const jm=a.jdataMetrics([{games:1000,diff:100,expectedSetting:2,p4:.2},{games:3000,diff:500,expectedSetting:6,p4:.8}]);
if(jm.avgG!==2000||jm.avgDiff!==300||Math.abs(jm.expectedSetting-4)>1e-9||Math.abs(jm.positiveRate-1)>1e-9||Math.abs(jm.p4-.5)>1e-9)throw new Error('Juggler data KPI aggregation broken');
a._set({shops:[],externalDays:[{id:1,shop:'データ店',date:'2026-08-24',machines:[{machine:'im',tableNo:'1',games:1000,diff:100,bb:4,rb:3,expectedSetting:2,p4:.2},{machine:'im',tableNo:'2',games:3000,diff:500,bb:12,rb:11,expectedSetting:6,p4:.8}]}]});
a.renderJugglerDataSite();
if(!String(elems.get('JDATA_OVERVIEW').innerHTML).includes('平均差枚')||!String(elems.get('JDATA_OVERVIEW').innerHTML).includes('+300枚'))throw new Error('Juggler data page render broken');

const relayBulk=await a.normalizeExternalBulkImport({format:'juggler-external-import-bulk',version:6,source:'ana-slo',shop:'Launcher新店舗',days:[{date:'2026-08-21',machines:raw.machines}]});
await a.importRelayBulk(relayBulk);
if(!a.storeDataShopNames().includes('Launcher新店舗'))throw new Error('relay import did not auto-add unseen shop');
console.log('app smoke: ok','judgeES',a.expectedSetting(j.q).toFixed(3),'jsonES',day.machines[0].expectedSetting.toFixed(3));
