import fs from 'node:fs';
const code=fs.readFileSync(new URL('../ana-launcher.js',import.meta.url),'utf8');
if(!code.includes("const VERSION='4.8.6'")) throw new Error('launcher version not 4.8.6');
if(!code.includes('jacExportMask')||!code.includes('jacExportText')||!code.includes('jacExportCopy')) throw new Error('dedicated export panel missing');
if(!code.includes("document.execCommand('copy')===true")) throw new Error('legacy copy result is not checked');
if(code.includes("alert(`${label}をコピーしたよ`)")) throw new Error('old unconditional copy-success alert remains');
if(!code.includes('Safariが自動コピーを許可しなかったよ')) throw new Error('copy failure fallback guidance missing');
if(!code.includes('selectExportText()')) throw new Error('manual-select fallback missing');
if(!code.includes('sharePreparedJson')) throw new Error('share/file-save fallback missing');
console.log('launcher export: ok');
