import fs from 'node:fs';
import vm from 'node:vm';
const src=fs.readFileSync(new URL('../ana-launcher.js',import.meta.url),'utf8');
if(!src.includes("const VERSION='4.5.0'")) throw new Error('launcher version not 4.5.0');
if(!src.includes("const RELAY_API='https://jugglerest.netlify.app/api/relay'")) throw new Error('relay API missing');
if(!src.includes("const RELAY_BRIDGE='https://jugglerest.netlify.app/relay-bridge.html'")) throw new Error('relay bridge missing');
if(!src.includes('relayCallBridge')||!src.includes('relayCallDirect')) throw new Error('bridge/direct fallback transport missing');
if(!src.includes('通信エラー詳細')||!src.includes('relayDiagText')) throw new Error('relay diagnostics missing');
if(!src.includes('jacRelayCode')||!src.includes('jacRelayPair')||!src.includes('jacRelaySend')) throw new Error('relay UI missing');
if(!src.includes("action:'claimPair'")||!src.includes("action:'send'")) throw new Error('relay claim/send actions missing');
if(!src.includes('RELAY_CHUNK_BYTES=2500000')||!src.includes('RELAY_CHUNK_DAYS=45')) throw new Error('relay chunk limits missing');
const a=src.indexOf('function relayCompactDay');
const b=src.indexOf('async function relayCall',a);
if(a<0||b<0) throw new Error('relay chunk core not found');
const code=`const shopName='テスト店',slug='test-shop',RELAY_CHUNK_DAYS=45,RELAY_CHUNK_BYTES=2500000;${src.slice(a,b)};globalThis.__R={relayPayload,relayChunks};`;
const ctx={globalThis:null,Blob,JSON,Math,Array,Object,String,Number,Set,Map};ctx.globalThis=ctx;
vm.createContext(ctx);vm.runInContext(code,ctx);
const days=Array.from({length:180},(_,i)=>({date:`2026-08-${String((i%28)+1).padStart(2,'0')}-${i}`,sourceUrl:'x',machines:[{machine:'im',tableNo:String(i),games:8000,diff:100,bb:30,rb:28,sourceMachineName:'ignored'}]}));
const chunks=ctx.__R.relayChunks(days);
if(chunks.length<4) throw new Error('180 days should be split into at least 4 chunks');
if(chunks.some(x=>x.days.length>45)) throw new Error('chunk exceeds 45 days');
if(chunks.flatMap(x=>x.days).length!==180) throw new Error('chunk day loss');
if(chunks.some(x=>x.days.some(d=>d.machines.some(m=>!('sourceMachineName' in m))))) throw new Error('sourceMachineName should be preserved for canonical alias traceability');
const longDays=Array.from({length:397},(_,i)=>({date:`2025-07-${String((i%28)+1).padStart(2,'0')}-${i}`,sourceUrl:'x',machines:[{machine:'my',tableNo:String(i),games:7000,diff:0,bb:25,rb:24}]}));
const longChunks=ctx.__R.relayChunks(longDays);if(longChunks.some(x=>x.days.length>45)||longChunks.flatMap(x=>x.days).length!==397)throw new Error('13-month relay chunking broken');
console.log('launcher relay: ok',chunks.length,'chunks');
