const fs=require('fs'), vm=require('vm'), {performance}=require('perf_hooks');
const html=fs.readFileSync(require('path').join(__dirname,'../public/index.html'),'utf8');
let m=html.match(/<script>([\s\S]*?)<\/script>/i); if(!m) throw new Error('script missing');
let code=m[1];
const cut=code.indexOf('let didRestore=restoreSavedState();');
if(cut<0) throw new Error('init cut missing');
code=code.slice(0,cut)+`nextFrame=()=>Promise.resolve();globalThis.__API={M,MACHINE_KEYS,externalJudge,expectedSetting,brutePrepare,bruteGenerate,bruteForecastRows,bruteForecastPrep,bruteConfirmSchema,bruteConfirmFdr,bruteEvidenceClusters,BRUTE_DIM_DEFS,bruteCombos,setExternalDays:x=>{externalDays=x},styleRates};\n})();`;
function fakeElement(){const base={value:'',checked:false,innerHTML:'',textContent:'',className:'',style:{},dataset:{},files:[],disabled:false,classList:{add(){},remove(){},toggle(){},contains(){return false}},appendChild(){},append(){},remove(){},click(){},focus(){},scrollIntoView(){},setAttribute(){},removeAttribute(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return fakeElement()},closest(){return fakeElement()}};return new Proxy(base,{get(t,p){if(p in t)return t[p];if(p==='length')return 0;return undefined},set(t,p,v){t[p]=v;return true}})}
const elems=new Map();global.document={getElementById(id){if(!elems.has(id))elems.set(id,fakeElement());return elems.get(id)},querySelectorAll(){return[]},querySelector(){return fakeElement()},createElement(){return fakeElement()},body:fakeElement(),addEventListener(){},removeEventListener(){}};const storage=new Map();global.window=global;global.location={protocol:'data:',reload(){}};global.localStorage={setItem(k,v){storage.set(k,String(v))},getItem(k){return storage.has(k)?storage.get(k):null},removeItem(k){storage.delete(k)}};global.indexedDB=undefined;global.confirm=()=>true;global.alert=()=>{};global.prompt=()=>null;global.navigator={};global.FileReader=function(){};if(!global.URL)global.URL={};global.URL.createObjectURL=()=> 'blob:x';global.URL.revokeObjectURL=()=>{};global.window.addEventListener=()=>{};global.window.removeEventListener=()=>{};eval(code);const A=global.__API;

function rng32(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function normal(rng){let u=0,v=0;while(!u)u=rng();while(!v)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function poisson(lambda,rng){if(lambda<=0)return 0;if(lambda>30)return Math.max(0,Math.round(lambda+Math.sqrt(lambda)*normal(rng)));let L=Math.exp(-lambda),p=1,k=0;do{k++;p*=rng()}while(p>L);return k-1}
function binom(n,p,rng){let mu=n*p;if(mu<30)return Math.min(n,poisson(mu,rng));return Math.max(0,Math.min(n,Math.round(mu+Math.sqrt(n*p*(1-p))*normal(rng))))}
function sampleDist(dist,rng){let x=rng(),c=0;for(let i=0;i<dist.length;i++){c+=dist[i];if(x<c)return i+1}return dist.length}
function blend(a,b,w){return a.map((x,i)=>x*(1-w)+b[i]*w)}
function ymd(d){return d.toISOString().slice(0,10)}
function plusDays(s,n){let d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return ymd(d)}
const BASE=[.45,.22,.15,.09,.06,.03], HIGH=[.08,.10,.12,.23,.24,.23];
const machineStarts={my:2001,im:2013,go:2025,fk:2037,hp:2049,gg:2061,mr:2073,um:2085};
const tables=[];for(const machine of A.MACHINE_KEYS)for(let i=0;i<12;i++)tables.push({machine,tableNo:String(machineStarts[machine]+i)});
function gamesSample(rng){let u=rng();if(u<.05)return 300+Math.floor(rng()*900);if(u<.20)return 1200+Math.floor(rng()*1800);if(u<.70)return 3000+Math.floor(rng()*5000);return 8000+Math.floor(rng()*3001)}
function rowFromSetting(machine,tableNo,date,setting,rng){let M=A.M[machine],t=M.simple[setting-1],G=gamesSample(rng),B=poisson(G/t.b,rng),R=poisson(G/t.r,rng);if(B+R>G){let z=G/(B+R);B=Math.floor(B*z);R=Math.floor(R*z)}let styles=(machine==='hp'||machine==='mr')?['random','cherry','perfect']:['random','cherry'],sw=(machine==='hp'||machine==='mr')?[.45,.45,.10]:[.5,.5],u=rng(),acc=0,style=styles[0];for(let i=0;i<styles.length;i++){acc+=sw[i];if(u<=acc){style=styles[i];break}}let rt=A.styleRates(machine,style),V=binom(G,1/t.g,rng),re=binom(G,1/M.replay,rng),ch=binom(G,rt.c*(1/M.revch[setting-1]),rng),be=binom(G,rt.b*(1/M.bell),rng),pi=binom(G,rt.p*(1/M.pier),rng),other=3*re+(M.chpay||2)*ch+14*be+10*pi,bonus=M.bbpay*B+M.regpay*R,diff=8*V-3*G+bonus-(B+R)+other;diff=Math.round(diff);let j=A.externalJudge(machine,G,B,R,diff);if(!j)throw new Error('judge failed');let q=j.q;return{machine,machineName:M.name,tableNo,games:G,diff,bb:B,rb:R,q,expectedSetting:A.expectedSetting(q),p4:q[3]+q[4]+q[5],p5:q[4]+q[5],p6:q[5],_trueSetting:setting,_style:style}}
function tableHist(history,key,n){let a=history.get(key)||[];return a.slice(-n)}
function trueDistFor(type,dayIndex,date,tbl,history,strength='strong'){
 if(type==='weak'&&strength==='strong')strength='weak';
 let d=new Date(date+'T12:00:00Z'),dom=d.getUTCDate(),dow=d.getUTCDay(),tail=Number(tbl.tableNo)%10,key=tbl.machine+'|'+tbl.tableNo,h=history.get(key)||[],alpha=0;
 const w=strength==='weak'?0.20:0.62;
 if(type==='random')return BASE;
 if(type==='simple'){if(tbl.machine==='im'&&dom%10===8)alpha=Math.max(alpha,.72);return blend(BASE,HIGH,alpha)}
 if(type==='strong'||type==='weak'){
  if(tbl.machine==='im'&&dom%10===8)alpha=1-(1-alpha)*(1-(strength==='weak'?.22:.72));
  if(tbl.machine==='my'&&dom%10===7)alpha=1-(1-alpha)*(1-(strength==='weak'?.18:.58));
  if(tbl.machine==='go'&&dow===6&&tail===3)alpha=1-(1-alpha)*(1-(strength==='weak'?.25:.78));
  let h7=h.slice(-7);if(h7.length===7){let sum=h7.reduce((s,r)=>s+r.diff,0),loss=h7.filter(r=>r.diff<0).length;if(sum<=-7000)alpha=1-(1-alpha)*(1-(strength==='weak'?.14:.50));if(loss>=5)alpha=1-(1-alpha)*(1-(strength==='weak'?.12:.42))}
  let prev=h[h.length-1];if(prev){if(prev.bb+prev.rb===0)alpha=1-(1-alpha)*(1-(strength==='weak'?.18:.60));if(prev._trueSetting>=5)alpha=1-(1-alpha)*(1-(strength==='weak'?.12:.36))}
  return blend(BASE,HIGH,Math.min(.90,alpha));
 }
 if(type==='regime'){
  if(dayIndex<90){if(tbl.machine==='im'&&dom%10===8)alpha=.74;if(tbl.machine==='go'&&dow===6&&tail===3)alpha=Math.max(alpha,.72)}
  else {if(tbl.machine==='my'&&dom%10===7)alpha=.72;if(tbl.machine==='fk'&&dow===2&&tail===6)alpha=Math.max(alpha,.74)}
  return blend(BASE,HIGH,alpha)
 }
 if(type==='unrep'){
  const n=Number(tbl.tableNo),prime=n>1&&(()=>{for(let i=2;i*i<=n;i++)if(n%i===0)return false;return true})();
  if(dayIndex%8===0&&prime)alpha=.86;return blend(BASE,HIGH,alpha)
 }
 return BASE
}
function makeStore(type,seed,days=180,strength){let rng=rng32(seed),start='2026-03-01',history=new Map(),out=[];for(let di=0;di<days;di++){let date=plusDays(start,di),machines=[];for(const tbl of tables){let dist=trueDistFor(type,di,date,tbl,history,strength),setting=sampleDist(dist,rng),r=rowFromSetting(tbl.machine,tbl.tableNo,date,setting,rng);machines.push({...r,_trueDist:dist});let key=tbl.machine+'|'+tbl.tableNo;if(!history.has(key))history.set(key,[]);history.get(key).push(r)}out.push({id:di+1,source:'sim',date,shop:'SIM',machines})}return{days:out,history,start,nextDate:plusDays(start,days),dayIndex:days,type,strength,seed}}
function stripTruth(days){return days.map(d=>({...d,machines:d.machines.map(({_trueSetting,_style,_trueDist,...r})=>r)}))}
function targetTruth(sim){let arr=[];for(const tbl of tables){let dist=trueDistFor(sim.type,sim.dayIndex,sim.nextDate,tbl,sim.history,sim.strength);arr.push({...tbl,dist,exp:dist.reduce((s,p,i)=>s+p*(i+1),0),p4:dist[3]+dist[4]+dist[5]})}return arr}
function metricsForRanks(rows,truth){let map=new Map(truth.map(x=>[x.machine+'|'+x.tableNo,x])),allP4=truth.reduce((s,x)=>s+x.p4,0)/truth.length,allES=truth.reduce((s,x)=>s+x.exp,0)/truth.length;let take=n=>{let xs=rows.filter(x=>x.evidence&&x.evidence.length).slice(0,n).map(r=>map.get(r.machine+'|'+r.tableNo)).filter(Boolean);return{n:xs.length,es:xs.length?xs.reduce((s,x)=>s+x.exp,0)/xs.length:NaN,p4:xs.length?xs.reduce((s,x)=>s+x.p4,0)/xs.length:NaN,lift:xs.length?(xs.reduce((s,x)=>s+x.p4,0)/xs.length)/allP4:NaN}};return{allP4,allES,top1:take(1),top5:take(5),top10:take(10)}}
function recover(cands,type){let sa=cands.filter(c=>c.grade==='S'||c.grade==='A'),rules=[];if(type==='simple'||type==='strong'||type==='weak')rules.push(c=>c.kind==='machine'&&c.machine==='im'&&c.dims.includes('dateTail')&&c.vals[c.dims.indexOf('dateTail')]==='末尾8');if(type==='strong'||type==='weak'){rules.push(c=>c.kind==='machine'&&c.machine==='my'&&c.dims.includes('dateTail')&&c.vals[c.dims.indexOf('dateTail')]==='末尾7');rules.push(c=>c.kind==='machine'&&c.machine==='go'&&c.dims.includes('weekday')&&c.vals[c.dims.indexOf('weekday')]==='土曜'&&c.dims.includes('tableTail')&&c.vals[c.dims.indexOf('tableTail')]==='末尾3')}return{total:rules.length,hit:rules.filter(f=>sa.some(f)).length}}
async function run(type,seed,maxDims=2,strength,daysN=180,analysisPeriod='all'){global.gc&&global.gc();let mem0=process.memoryUsage().heapUsed,t0=performance.now(),sim=makeStore(type,seed,daysN,strength),genMs=performance.now()-t0,clean=stripTruth(sim.days);A.setExternalDays(clean);let prep=A.brutePrepare('SIM',analysisPeriod,2000,clean),t1=performance.now(),all=await A.bruteGenerate(prep,maxDims,4,(p,n)=>{let z=Math.floor(p*20);if(z!==global.__lastProg){global.__lastProg=z;console.error(`PROG ${(p*100).toFixed(0)}% cand=${n} t=${((performance.now()-t1)/1000).toFixed(1)}s`)}}),analysisMs=performance.now()-t1;console.error('BEFORE_FORECAST');A.setExternalDays(clean);let ft0=performance.now(),rows=A.bruteForecastRows({prep,all},sim.nextDate),forecastMs=performance.now()-ft0;console.error('AFTER_FORECAST',forecastMs),truth=targetTruth(sim),met=metricsForRanks(rows,truth),counts={S:0,A:0,B:0,C:0};for(const c of all)counts[c.grade]=(counts[c.grade]||0)+1;let rec=recover(all,type),mem1=process.memoryUsage().heapUsed;return{type,seed,maxDims,analysisPeriod,rows:prep.rows.length,candidates:(all._summary?.tested??all.length),retained:all.length,confirmSelected:(all._summary?.confirmSelected??all.filter(c=>c.confirmSelected).length),confirmSig:(all._summary?.confirmSignificant??all.filter(c=>c.confirmSelected&&c.qConfirm<=.05&&c.effect>0).length),exploreSig:(all._summary?.fdrSignificant??all.filter(c=>c.q<=.05&&c.effect>0).length),...counts,recovery:rec,forecastCandidates:rows.filter(x=>x.evidence.length&&x.aimScore>=52&&x.uplift>=.08&&x.evidenceConf>=69).length,metrics:met,genSec:+(genMs/1000).toFixed(2),analysisSec:+(analysisMs/1000).toFixed(2),forecastSec:+(forecastMs/1000).toFixed(3),heapDeltaMB:+((mem1-mem0)/1048576).toFixed(1),topForecast:rows.slice(0,12).map(r=>({machine:r.machine,tableNo:r.tableNo,aim:r.aimScore,uplift:+r.uplift.toFixed(3),conf:+r.evidenceConf.toFixed(1),ev:r.evidence.map(c=>c.label)})),topSA:all.filter(c=>c.grade==='S'||c.grade==='A').sort((a,b)=>b.priority-a.priority).slice(0,8).map(c=>({grade:c.grade,label:c.label,q:+c.qConfirm.toFixed(4),qg:+c.qConfirmGlobal.toFixed(4),eff:+c.effect.toFixed(3),val:+c.valEffect.toFixed(3),oos:+c.oosEffect.toFixed(3),b6:+((c.block6WinRate||0).toFixed(2))})),ruleDiag:all.filter(c=>c.kind==='machine'&&c.machine==='im'&&c.dims.includes('dateTail')&&c.vals[c.dims.indexOf('dateTail')]==='末尾8').sort((a,b)=>a.dims.length-b.dims.length||b.priority-a.priority).slice(0,12).map(c=>({grade:c.grade,label:c.label,p:+c.p.toFixed(6),pv:+c.pVal.toFixed(6),q:+c.qConfirm.toFixed(4),qw:+c.qConfirmWithin.toFixed(4),qf:+c.qConfirmFamily.toFixed(4),qg:+c.qConfirmGlobal.toFixed(4),qs:+c.qConfirmStrict.toFixed(4),eff:+c.effect.toFixed(3),disc:+c.discEffect.toFixed(3),val:+c.valEffect.toFixed(3),oos:+c.oosEffect.toFixed(3),ow:+c.oosWinRate.toFixed(2),b6:+(c.block6WinRate||0).toFixed(2),conf:+c.confidence.toFixed(1),str:+c.strength.toFixed(1),sel:c.confirmSelected}))};}
(async()=>{let args=process.argv.slice(2),type=args[0]||'random',seed=+(args[1]||1),dims=+(args[2]||2),strength=args[3],daysN=+(args[4]||180);let analysisPeriod=args[5]||'all',r=await run(type,seed,dims,strength,daysN,analysisPeriod);console.log(JSON.stringify(r,null,2))})().catch(e=>{console.error(e);process.exit(1)});
