from pathlib import Path
from playwright.sync_api import sync_playwright
import base64
root=Path(__file__).resolve().parents[1];js=(root/'public/app-v510.js').read_text();css=(root/'public/app-v510.css').read_text();js=js.replace("link.href='./app-v510.css'","link.href='data:text/css;base64,"+base64.b64encode(css.encode()).decode()+"'");js=js.replace('./assets/jugest-mark.png','data:image/png;base64,'+base64.b64encode((root/'public/assets/jugest-mark.png').read_bytes()).decode())
bridge="""<script>let listeners=new Set(),bal=1200,name='Alpha店',balCalls=0,renameCalls=0;window.JUGEST_CORE_BRIDGE={getSummary(){return{storeCount:1,runCount:2,externalDayCount:0,linked:false,pending:0,enabledTargets:0,errorTargets:0,missingDays:0,unregistered:0,syncLabel:'未同期'}},getStores(){return[{name,latestDate:'',registered:false,error:false}]},getActiveStore(){return name},setActiveStore(){},subscribe(f){listeners.add(f);return()=>listeners.delete(f)},getStoreFinance(){return{summary:{stores:1,currentSaved:bal,cashDiff:5000,actualDiff:800},rows:[{id:'1',name,runs:2,totalG:6200,currentSaved:bal,savedDelta:200,cashDiff:5000,actualDiff:800,actualN:2,actualRate:101.2,expectedSetting:4.1,history:[]}]}},setStoreSavedBalance(id,target){balCalls++;bal=+target;listeners.forEach(f=>f());return this.getStoreFinance()},async renameStore(id,n){renameCalls++;name=n;listeners.forEach(f=>f());return this.getStoreFinance()}};</script>"""
html='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0}</style>'+bridge+'<jugest-app></jugest-app><script>'+js+'</script>'
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox']);page=b.new_page(viewport={'width':390,'height':844});page.set_content(html);page.wait_for_timeout(80);host=page.locator('jugest-app')
 def click(sel):host.evaluate(f"e=>e.shadowRoot.querySelector('{sel}').click()");page.wait_for_timeout(50)
 def setv(sel,val):host.evaluate("(e,a)=>{let x=e.shadowRoot.querySelector(a.s);x.value=a.v;x.dispatchEvent(new Event('input',{bubbles:true}))}",{'s':sel,'v':val});page.wait_for_timeout(25)
 click('[data-workspace=records]');click('[data-action=records-stores]');click('[data-store-finance-balance]');setv('[data-store-finance-value]','2500');click('[data-store-finance-save]');assert page.evaluate('balCalls')==1;click('[data-store-finance-rename]');setv('[data-store-finance-value]','Beta店');click('[data-store-finance-save]');assert page.evaluate('renameCalls')==1;assert 'Beta店' in host.evaluate("e=>e.shadowRoot.querySelector('.store-finance-list').innerText")
 d=host.evaluate("e=>{let x=e.shadowRoot.querySelector('.app-shell');return[x.scrollWidth,x.clientWidth]}");assert d[0]<=d[1],d;b.close()
print('v5.1.0 native store finance browser PASS')
