from pathlib import Path
from playwright.sync_api import sync_playwright
import base64
root=Path(__file__).resolve().parents[1]
js=(root/'public/app-v510.js').read_text();css=(root/'public/app-v510.css').read_text()
css_data='data:text/css;base64,'+base64.b64encode(css.encode()).decode();js=js.replace("link.href='./app-v510.css'", "link.href='"+css_data+"'")
img_data='data:image/png;base64,'+base64.b64encode((root/'public/assets/jugest-mark.png').read_bytes()).decode();js=js.replace('./assets/jugest-mark.png',img_data)
bridge=r'''<script>
let listeners=new Set(),pickup=null,compare=[{id:1,label:'412',machine:'im',style:'random',G:'',B:'',R:'',D:''}],moveTarget=null,moveCalls=0;
const machines=[{key:'im',name:'アイムジャグラーEX'},{key:'my',name:'マイジャグラーV'}];
function rev(input={}){const G=+input.G||0;return{machine:input.machine||'im',machineName:'アイムジャグラーEX',machines,styles:[{value:'random',label:'適当打ち'},{value:'cherry',label:'チェリー狙い'}],style:input.style||'random',G,B:+input.B||0,R:+input.R||0,D:input.D??'',expectedSetting:G?4.31:0,p4:G?.74:0,p5:G?.43:0,p6:G?.19:0,denom:G?6.18:null,estimatedCount:G?388:null,warning:''}}
function pickupState(){if(!pickup)return null;let self=Math.max(0,pickup.currentG-pickup.startG);return{...pickup,selfG:self,expectedSetting:self?4.55:4.31,p4:self?.79:.74,p5:self?.48:.43,p6:self?.22:.19,warning:'',defs:[{id:'grape',name:'ぶどう',group:'small',value:pickup.v.grape||0,enabled:pickup.on.grape!==false},{id:'bb',name:'BIG',group:'big',value:pickup.v.bb||0,enabled:pickup.on.bb!==false},{id:'rb',name:'REG',group:'reg',value:pickup.v.rb||0,enabled:pickup.on.rb!==false}]}}
function compareState(bucket='all',sort='p4'){let ranking=compare.filter(r=>r.G&&String(r.D)!=='').map((r,i)=>({id:r.id,label:r.label||`台${i+1}`,machine:r.machine,machineName:r.machine==='my'?'マイジャグラーV':'アイムジャグラーEX',styleLabel:'適当打ち',p4:.7+i*.05,p5:.4,p6:.2,avg:4.2+i*.1}));return{bucket,sort,machines,rows:compare.map(r=>({...r,styles:[{value:'random',label:'適当打ち'}],status:r.G?'':'Gと差枚を入れるとランキングに反映'})),ranking}}
window.JUGEST_CORE_BRIDGE={getSummary(){return{storeCount:2,runCount:1,externalDayCount:10,linked:true,enabledTargets:1,syncLabel:'18:55'}},getStores(){return[{name:'エスパス日拓新宿歌舞伎町店',registered:true,latestDate:'2026-09-05'}]},getActiveStore(){return'エスパス日拓新宿歌舞伎町店'},setActiveStore(){return true},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},getJudgeState(){return{machine:'im',machines,context:{shopName:'エスパス日拓新宿歌舞伎町店',date:'2026-09-05',tableNo:'401'}}},getReverseStyles(){return[{value:'random',label:'適当打ち'},{value:'cherry',label:'チェリー狙い'}]},getReverseState:rev,beginPickup(input){pickup={machine:input.machine||'im',machineName:'アイムジャグラーEX',startG:+input.G,currentG:+input.G,startedAt:'18:55',style:'random',styleLabel:'適当打ち',B:+input.B||0,R:+input.R||0,D:+input.D||0,v:{},on:{}};return pickupState()},getPickupState(){return pickupState()},setPickupCurrentG(m,v){pickup.currentG=+v||0;return pickupState()},setPickupStartG(m,v){pickup.startG=+v||0;return pickupState()},setPickupMetric(m,id,v){pickup.v[id]=+v||0;return pickupState()},setPickupMetricEnabled(m,id,v){pickup.on[id]=!!v;return pickupState()},endPickup(){pickup=null},getCompareState:compareState,addCompareRow(){compare.push({id:compare.length+1,label:'',machine:'im',style:'random',G:'',B:'',R:'',D:''});return compareState()},updateCompareRow(bucket,id,p){Object.assign(compare.find(r=>String(r.id)===String(id)),p);return compareState()},deleteCompareRow(bucket,id){compare=compare.filter(r=>String(r.id)!==String(id));return compareState()},clearCompareRows(){compare=[];return compareState()},getMoveState(){return{context:{tableNo:'401',machineName:'アイムジャグラーEX'},current:{combinedP4:.62},candidates:[{machine:'im',machineName:'アイムジャグラーEX',tableNo:'412',predP4:.73,predES:4.4,gap:.11}],target:moveTarget,history:[],message:''}},selectMoveTarget(m,t){moveTarget={machine:m,machineName:'アイムジャグラーEX',tableNo:t,priorP4:.73,g:'',bb:'',rb:'',diff:''};return this.getMoveState()},calculateMoveCompare(){moveCalls++;return{decision:'移動検討',gap:.08,targetP4:.75,currentP4:.67}}};
</script>'''
html='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>html,body{margin:0;background:#f9fbff}</style>'+bridge+'<jugest-app></jugest-app><script>'+js+'</script>'
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage']);page=b.new_page(viewport={'width':390,'height':844});errs=[];page.on('pageerror',lambda e:errs.append(str(e)));page.set_content(html,wait_until='domcontentloaded');page.wait_for_timeout(150);host=page.locator('jugest-app')
 def click(sel): host.evaluate(f"e=>e.shadowRoot.querySelector('{sel}').click()");page.wait_for_timeout(70)
 click('[data-workspace=live]');click('[data-action=live-rev]');assert host.evaluate("e=>!!e.shadowRoot.querySelector('.reverse-screen')")
 host.evaluate("e=>{for(const [s,v] of [['[data-rev-g]','2400'],['[data-rev-b]','10'],['[data-rev-r]','9'],['[data-rev-d]','850']]){let x=e.shadowRoot.querySelector(s);x.value=v;x.dispatchEvent(new Event('input',{bubbles:true}))}}")
 assert host.evaluate("e=>e.shadowRoot.querySelector('[data-rev-es]').textContent")=='4.31';click('[data-pickup-begin]');assert host.evaluate("e=>!!e.shadowRoot.querySelector('.pickup-wrap')")
 host.evaluate("e=>{let x=e.shadowRoot.querySelector('[data-pickup-current-g]');x.focus();x.value='3000';x.dispatchEvent(new Event('input',{bubbles:true}))}");assert host.evaluate("e=>e.shadowRoot.activeElement===e.shadowRoot.querySelector('[data-pickup-current-g]')");assert host.evaluate("e=>e.shadowRoot.querySelector('[data-pickup-self]').textContent")=='600G'
 dims=host.evaluate("e=>({sw:e.shadowRoot.querySelector('.app-shell').scrollWidth,cw:e.shadowRoot.querySelector('.app-shell').clientWidth})");assert dims['sw']<=dims['cw'],dims
 click('[data-action=live-move]');click('[data-move-candidate]');assert host.evaluate("e=>!!e.shadowRoot.querySelector('[data-move-calc]')");host.evaluate("e=>{let x=e.shadowRoot.querySelector('[data-move-g]');x.value='1800';x.dispatchEvent(new Event('input',{bubbles:true}))}");click('[data-move-calc]');assert page.evaluate('moveCalls')==1;assert '移動検討' in host.evaluate("e=>e.shadowRoot.querySelector('.move-decision').innerText")
 click('[data-action=live-compare]');assert host.evaluate("e=>!!e.shadowRoot.querySelector('[data-compare-row]')");host.evaluate("e=>{let row=e.shadowRoot.querySelector('[data-compare-row]');for(const [f,v] of [['G','3000'],['B','12'],['R','10'],['D','900']]){let x=row.querySelector(`[data-field=${f}]`);x.value=v;x.dispatchEvent(new Event('input',{bubbles:true}))}}")
 assert host.evaluate("e=>e.shadowRoot.querySelectorAll('.ranking-row').length")>=1
 dims=host.evaluate("e=>({sw:e.shadowRoot.querySelector('.app-shell').scrollWidth,cw:e.shadowRoot.querySelector('.app-shell').clientWidth})");assert dims['sw']<=dims['cw'],dims
 assert not errs,errs;b.close()
print('v5.1.0 Phase 4 browser harness PASS')
