from pathlib import Path
p=Path('index.html');s=p.read_text()
a=s.index('function syncPendingFromForm(){');b=s.index('function finalizeRunRecord(){',a)
block=r'''function numberOrNull(v){let t=String(v??"").trim();if(t==="")return null;let n=+t;return Number.isFinite(n)?n:null}
function positiveOrNull(v){let n=numberOrNull(v);return n!=null&&n>0?n:null}
function runFinance(p){let loan=positiveOrNull(p?.loanCoinsPer1000),exchange=positiveOrNull(p?.exchangeCoinsPer1000),savedInvest=Math.max(0,numberOrNull(p?.savedInvestCoins)??0),cashInvest=Math.max(0,numberOrNull(p?.cashInvestYen)??0),collected=numberOrNull(p?.collectedCoins),exchangedYen=Math.max(0,numberOrNull(p?.exchangedYen)??0),override=numberOrNull(p?.exchangeUsedCoinsOverride);let cashBorrowedCoins=cashInvest===0?0:(loan?cashInvest/1000*loan:NaN),totalInvestCoins=Number.isFinite(cashBorrowedCoins)?savedInvest+cashBorrowedCoins:NaN,actualDiff=collected!=null&&Number.isFinite(totalInvestCoins)?collected-totalInvestCoins:NaN;let exchangeUsedCoins=override!=null?Math.max(0,override):(exchangedYen===0?0:(exchange?exchangedYen/1000*exchange:NaN)),savedCoinDelta=collected!=null&&Number.isFinite(exchangeUsedCoins)?collected-savedInvest-exchangeUsedCoins:NaN,cashDiff=exchangedYen-cashInvest,valueProfit=exchange&&Number.isFinite(savedCoinDelta)?cashDiff+savedCoinDelta/exchange*1000:NaN;return{loanCoinsPer1000:loan,exchangeCoinsPer1000:exchange,savedInvestCoins:savedInvest,cashInvestYen:cashInvest,collectedCoins:collected,exchangedYen,exchangeUsedCoins,cashBorrowedCoins,totalInvestCoins,actualDiff,cashDiff,savedCoinDelta,valueProfit}}
function financeInputActive(p){return +p?.financeVersion>=2||[p?.savedInvestCoins,p?.cashInvestYen,p?.collectedCoins,p?.exchangedYen,p?.exchangeUsedCoinsOverride].some(v=>String(v??"").trim()!=="")}
function selectedRunShop(){return shops.find(x=>String(x.id)===String($("LOG_SHOP")?.value||pendingSession?.shopId||""))||null}
function syncPendingFromForm(){if(!pendingSession)return;pendingSession.date=$("LOG_DATE").value||localDateString();pendingSession.tableNo=$("LOG_TABLE").value.trim();pendingSession.startG=Math.max(0,+$("LOG_START_G").value||0);pendingSession.endG=Math.max(0,+$("LOG_END_G").value||0);pendingSession.playedG=Math.max(0,pendingSession.endG-pendingSession.startG);pendingSession.loanCoinsPer1000=$("LOG_LOAN_RATE").value.trim();pendingSession.exchangeCoinsPer1000=$("LOG_EXCHANGE_RATE").value.trim();pendingSession.savedInvestCoins=$("LOG_SAVED_INVEST").value.trim();pendingSession.cashInvestYen=$("LOG_CASH_INVEST").value.trim();pendingSession.collectedCoins=$("LOG_COLLECTED").value.trim();pendingSession.exchangedYen=$("LOG_EXCHANGED_YEN").value.trim();pendingSession.exchangeUsedCoinsOverride=$("LOG_EXCHANGE_COINS_OVERRIDE").value.trim();if(+pendingSession.financeVersion>=2||[$("LOG_SAVED_INVEST"),$("LOG_CASH_INVEST"),$("LOG_COLLECTED"),$("LOG_EXCHANGED_YEN"),$("LOG_EXCHANGE_COINS_OVERRIDE")].some(e=>String(e.value||"").trim()!==""))pendingSession.financeVersion=2;pendingSession.shopId=$("LOG_SHOP").value||"";pendingSession.memo=$("LOG_MEMO").value;pendingSession.entryType=entryTypeOf(pendingSession);pendingSession.tagIds=sessionTagIds(pendingSession)}
["LOG_DATE","LOG_TABLE","LOG_START_G","LOG_END_G","LOG_LOAN_RATE","LOG_EXCHANGE_RATE","LOG_SAVED_INVEST","LOG_CASH_INVEST","LOG_COLLECTED","LOG_EXCHANGED_YEN","LOG_EXCHANGE_COINS_OVERRIDE","LOG_MEMO"].forEach(id=>{$(id).oninput=()=>{syncPendingFromForm();renderPendingExpectation();renderFinancePreview();queueAutoSave()};$(id).onchange=$(id).oninput});
$("LOG_SHOP").onchange=()=>{if(!pendingSession)return;pendingSession.shopId=$("LOG_SHOP").value||"";let sh=selectedRunShop();$("LOG_LOAN_RATE").value=Number.isFinite(+sh?.loanCoinsPer1000)&&+sh.loanCoinsPer1000>0?sh.loanCoinsPer1000:"";$("LOG_EXCHANGE_RATE").value=Number.isFinite(+sh?.exchangeCoinsPer1000)&&+sh.exchangeCoinsPer1000>0?sh.exchangeCoinsPer1000:"";syncPendingFromForm();renderFinancePreview();queueAutoSave()};
function renderPendingExpectation(){if(!pendingSession){$("LOG_EXPECT").innerHTML="";return}let g=+pendingSession.playedG||0,q=pendingSession.q,key=pendingSession.machine;let es=expectedSetting(q),ev=expectedDiffCoins(key,q,g);$("LOG_EXPECT").innerHTML=`<div class="s"><small>自分の実戦G</small><strong>${g.toLocaleString("ja-JP")}G</strong></div><div class="s"><small>期待設定</small><strong>${fmtSetting(es)}</strong></div><div class="s"><small>期待差枚</small><strong>${fmtCoins(ev)}</strong></div>`}
function renderFinancePreview(){let el=$("LOG_FINANCE_PREVIEW");if(!el)return;if(!pendingSession){el.innerHTML="";return}if(!financeInputActive(pendingSession)){el.innerHTML=`${hasActual(pendingSession)?`<div class="s"><small>旧形式 実差枚</small><strong>${fmtCoins(+pendingSession.actualDiff)}</strong></div>`:""}${hasCash(pendingSession)?`<div class="s"><small>旧形式 現金</small><strong>${fmtYen(+pendingSession.cashDiff)}</strong></div>`:""}${hasSavedDelta(pendingSession)?`<div class="s"><small>旧形式 貯メダル</small><strong>${fmtCoins(+pendingSession.savedCoinDelta)}</strong></div>`:""}`;return}let f=runFinance(pendingSession);el.innerHTML=`<div class="s"><small>総投資枚数</small><strong>${Number.isFinite(f.totalInvestCoins)?Math.round(f.totalInvestCoins).toLocaleString("ja-JP")+"枚":"—"}</strong></div><div class="s"><small>実差枚</small><strong>${fmtCoins(f.actualDiff)}</strong></div><div class="s"><small>現金収支</small><strong>${fmtYen(f.cashDiff)}</strong></div><div class="s"><small>貯メダル増減</small><strong>${fmtCoins(f.savedCoinDelta)}</strong></div><div class="s"><small>換金使用枚数</small><strong>${Number.isFinite(f.exchangeUsedCoins)?Math.round(f.exchangeUsedCoins).toLocaleString("ja-JP")+"枚":"—"}</strong></div><div class="s"><small>金額換算収支</small><strong>${fmtYen(f.valueProfit)}</strong></div>`}
function fillRunForm(){let f=$("LOG_FORM"),e=$("LOG_EMPTY");if(!pendingSession){f.style.display="none";e.style.display="block";$("LOG_FINANCE_PREVIEW").innerHTML="";return}f.style.display="block";e.style.display="none";let p=pendingSession,q=p.q,er=expectedRatePct(p.machine,q);$("LOG_SOURCE_SUMMARY").innerHTML=`<b>${M[p.machine].name}</b> / ${p.source==="live"?"合成判別":"判別用"} <span class="run-entry">${entryTypeLabel(p)}</span><br>最終期待設定 <b>${fmtSetting(expectedSetting(q))}</b> ・ 期待機械割 <b>${fmtPct(er,2)}</b>`;$("LOG_DATE").value=p.date||localDateString();$("LOG_TABLE").value=p.tableNo||"";$("LOG_START_G").value=p.startG??0;$("LOG_END_G").value=p.endG??0;$("LOG_SAVED_INVEST").value=p.savedInvestCoins??"";$("LOG_CASH_INVEST").value=p.cashInvestYen??"";$("LOG_COLLECTED").value=p.collectedCoins??"";$("LOG_EXCHANGED_YEN").value=p.exchangedYen??"";$("LOG_EXCHANGE_COINS_OVERRIDE").value=p.exchangeUsedCoinsOverride??"";$("LOG_MEMO").value=p.memo||"";refreshShopSelect(p.shopId);let sh=selectedRunShop();$("LOG_LOAN_RATE").value=p.loanCoinsPer1000??(Number.isFinite(+sh?.loanCoinsPer1000)&&+sh.loanCoinsPer1000>0?sh.loanCoinsPer1000:"");$("LOG_EXCHANGE_RATE").value=p.exchangeCoinsPer1000??(Number.isFinite(+sh?.exchangeCoinsPer1000)&&+sh.exchangeCoinsPer1000>0?sh.exchangeCoinsPer1000:"");if(+p.financeVersion>=2){p.loanCoinsPer1000=$("LOG_LOAN_RATE").value;p.exchangeCoinsPer1000=$("LOG_EXCHANGE_RATE").value}if($("LOG_NEW_SHOP")){if(p.v4Context?.isNew){$("LOG_NEW_SHOP").placeholder="新規店舗名をここで設定";$("LOG_NEW_SHOP").style.borderColor="#8d6b35"}else{$("LOG_NEW_SHOP").placeholder="未登録なら店舗名を入力";$("LOG_NEW_SHOP").style.borderColor=""}}renderTagControls();renderPendingExpectation();renderFinancePreview()}
'''
s=s[:a]+block+s[b:];p.write_text(s)
